### ISSUE TITLE
Entries are duplicated on new entry

### ISSUE THREAD

**Issue by mbremyk** [Snauweb/snauweb#1]
Sending a new suggestion appends all previous suggestions to previous suggestions list instead of overwriting.

To reproduce:
Send suggestion.
Without reloading the page, send another suggestion

Proposed fix:
Two different approaches are possible:
1. Clear previous suggestions list before writing all suggestions
2. Check which suggestions are new since last fetch and only fetch those

**Comment by Grimmbol** [comment]
Naive approach, all old DOM elements  in the list view are deleted and replaced upon load. Should not be a performance bottle neck yet, at least not compared to list load time
