### ISSUE TITLE
Suggestion box can be resized behind previous suggestions list

### ISSUE THREAD

**Issue by mbremyk** [Snauweb/snauweb#2]
When resizing the suggestion box it can be pulled behind the previous suggestions box. If dropped while the resize corner is behind the previous suggestions list it is not available for resize anymore.

How to reproduce:
Grab resize corner of suggestion box and pull right.
Drop corner while mouse is over previous suggestions box.

Proposed fix:
Lock the size of the suggestion box, either giving it a max width, or buy giving it an absolute width

**Comment by Grimmbol** [comment]
Quick fix, set resize: none på boksen
